repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Lint with Ruff
        entry: uv run ruff check
        language: system
        types: [python]
        
      - id: ruff-format
        name: Format with Ruff
        entry: uv run ruff format
        language: system
        types: [python]             
 
      - id: ty-check
        name: Type check with Ty
        entry: uv run ty check
        language: system
        types: [python]
      

