# This file is auto-generated by LitServe.
# Disable auto-generation by setting `generate_client_file=False` in `LitServer.run()`.

import requests

response = requests.post("http://127.0.0.1:8000/predict", json={"text": "hello"})
print(f"Status: {response.status_code}\nResponse:\n {response.text}")
