model_name: google/bert_uncased_L-2_H-128_A-2
data_dir: data/jigsaw-toxic-comment-classification-challenge
batch_size: 64
val_size: 0.2
num_labels: 6
label_names: null
max_token_len: 256
lr: 3.0e-05
warmup_start_lr: 3.0e-06
warmup_epochs: 5
max_epochs: 20
cache_dir: ./data
seed: 1234
fast_dev_run: false
