model_name: google/bert_uncased_L-2_H-128_A-2
data_dir: ./data/jigsaw-toxic-comment-classification-challenge
labels: null
batch_size: 64
val_size: 0.2
max_token_len: 256
lr: 3.0e-05
warmup_start_lr: 1.0e-05
warmup_epochs: 5
max_epochs: 20
patience: 3
run_name: bert-tiny
perf: false
fast_dev_run: false
seed: 18
